site_name: Dragonsoft Leitfaden für Schüler
site_url: https://nood3ls.github.io/dragonsoft-guide/
site_description: Ein Leitfaden für Schüler, die das Dragonsoft Spiel spielen möchten.
theme:
  font:
    text: Merriweather Sans
  name: material
  favicon: images/favicon.png
  logo: images/favicon.png
  features:
    - navigation.tabs
    - navigation.top
    - navigation.footer
  palette:
    primary: 'indigo'
    accent: 'indigo' 

nav:
  - Startseite: index.md
  - Installation: installation.md

extra: 
  social:
    - icon: simple/instagram
      link: https://instagram.com/dragonsoftgymsl
    - icon: fontawesome/solid/globe
      link: https://gymsl.agitalpro.de/
